In [6]:
import gym
import numpy as np

In [7]:
board_size = 9
gym = gym.make('gym_go:go-v0', size=board_size, komi=0, reward_method='real')

In [8]:
a, b, c, d = gym.step(4)

In [11]:
np.where(d['invalid_moves'][:-1] == 0)

(array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80], dtype=int64),)

In [35]:
from random import randrange
visits = np.array([(randrange(10), randrange(10)) for i in range(4)])

In [36]:
visits

array([[7, 1],
       [5, 6],
       [4, 3],
       [9, 5]])

In [50]:
temperature = 10
exps = np.exp(visits[:,0]/temperature)
probabilities = exps/np.sum(exps)
action_index = np.random.choice(np.arange(len(exps)), p=probabilities)

In [51]:
action_index

3

In [52]:
probabilities

array([0.26448367, 0.21654092, 0.19593432, 0.32304109])

In [42]:
action_index = np.argmax(visits[:,0])

In [43]:
action_index

3